[project]
name = "4g3-cw2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
link-mode = "copy"
dependencies = []

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
